Repository AdministratorNei/nei-almoxarifado-web, pull requests merged in 2024-07, with the labels that each got.

#60 Feat: Customizar fontes e fixar cabeçalho das tabelas
  components/dashboard/BarChartItems.vue
  components/dashboard/BarChartUtils.vue
  components/navbar/NavSideBar.vue
  components/tables/Table.vue
  pages/index.vue
Labels: enhancement

#61 [feat]: Estilizações das páginas de autenticação e páginas gerais
  app.vue
  assets/img/nei.png
  assets/img/teste.jpeg
  assets/scss/variables.scss
  components/Icons/Box.vue
  components/Icons/Report.vue
  components/buttons/configure.vue
  components/buttons/filter.vue
  components/buttons/newItem.vue
  components/header/Brand.vue
  components/header/Profile.vue
  components/header/SearchBar.vue
  components/header/nei/Profile.vue
  components/modal/ItemDetails.vue
  components/modal/Modal.vue
  components/popup/popup.vue
  components/tables/Table.vue
  components/utils/Search.vue
  layouts/authentication.vue
  layouts/default.vue
  layouts/profile.vue
  middleware/auth.global.ts
  middleware/error-handler.global.ts
  pages/atualizar-senha.vue
  pages/backup.vue
  pages/cadastro.vue
  pages/catalogo/index.vue
  pages/emailAuth.vue
  pages/index.vue
  pages/login.vue
  pages/nei/catalogo.vue
  pages/nei/index.vue
  pages/nei/solicitacoes.vue
  pages/recuperar-senha.vue
  pages/registro.vue
  services/items/itemsPATCH.ts
  services/requests/requestsGET.ts
  services/users/userPUT.ts
  stores/notifications.ts
  stores/user.ts
Labels: bug, enhancement

#62 [fix]: corrigido centralizações de elementos
  components/navbar/NavSideBar.vue
  pages/index.vue
Labels: bug
