Repository AdministratorNei/nei-almoxarifado-web, pull requests merged in 2024-09, with the labels that each got.

#69 feat: Adicionar conteúdo
  pages/catalogo/index.vue
  pages/controle-de-acesso.vue
  pages/perfil.vue
  pages/registro.vue
  pages/sobre.vue
Labels: enhancement

#71 Refactor: Corrigir informaçõess
  pages/nei/sobre.vue
  pages/sobre.vue
  public/foto_andriel.jpg
Labels: refactor

#74 feat: Mudanças pontuais
  components/footer/Footer.vue
  pages/catalogo/index.vue
  pages/nei/catalogo.vue
  pages/nei/configuracoes.vue
  pages/nei/index.vue
  pages/nei/perfil.vue
  pages/nei/sobre.vue
  pages/nei/solicitacoes.vue
  pages/sobre.vue
Labels: enhancement

#75 Fix: Corrigir alguns erros
  app.vue
  components/footer/Footer.vue
  components/header/nei/Header.vue
  components/modal/Modal.vue
  components/utils/Search.vue
  error.vue
  layouts/authentication.vue
  pages/atualizar-senha.vue
  pages/catalogo/index.vue
  pages/index.vue
  pages/login.vue
  pages/nei/catalogo.vue
  pages/perfil.vue
  pages/registro.vue
Labels: bug, enhancement, refactor

#76 fix: corrigido fundo mobile dos botões do catálogo
  pages/catalogo/index.vue
  pages/index.vue
  pages/nei/sobre.vue
  pages/registro.vue
Labels: bug

#77 fix: Algumas correções
  components/footer/Footer.vue
  components/modal/Search.vue
  components/titles/Title.vue
  layouts/client.vue
  layouts/default.vue
  pages/catalogo/index.vue
  pages/nei/catalogo.vue
  pages/nei/configuracoes.vue
  pages/nei/index.vue
  pages/nei/sobre.vue
  pages/nei/solicitacoes.vue
  pages/registro.vue
Labels: bug, enhancement

#78 fix: Correções pontuais
  pages/nei/solicitacoes.vue
Labels: bug

#79 feat: Adicionar pesquisas recentes
  components/modal/Search.vue
  components/utils/Search.vue
  pages/nei/catalogo.vue
  stores/search.ts
Labels: enhancement
